server:
  port: 8500
  #servlet:
    #context-path: "/v1"
spring:
  application:
    name: dbg-service-content
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:192.168.99.100}:${DB_PORT:3306}/${DB_NAME:dbg}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=FALSE
    username: ${DB_USER:root}
    password: ${DB_PWD:root}
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    minIdle: 5
    maxActive: 20
    #配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #验证连接是否有效。此参数必须设置为非空字符串，下面三项设置成true才能生效
    validationQuery: SELECT 1
    #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
    testWhileIdle: true
    #指明是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testOnBorrow: true
    #指明是否在归还到池中前进行检验
    testOnReturn: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:}
        ip: ${NACOS_CLIENT_ADDR:}

dubbo:
  scan:
    base-packages: club.dbg.cms.content.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: spring-cloud://localhost

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:club/dbg/cms/login/mapper/*.xml

logging:
  config: classpath:logback-spring.xml
  path: ./logs