server:
  port: 8910
  servlet:
    context-path: "/v1/pay"
spring:
  application:
    name: dbg-service-pay
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

alipay:
  serverUrl: ${SERVER_URL:https://openapi.alipaydev.com/gateway.do}
  appId: ${APP_ID:}
  privateKey: ${PRIVATE_KEY:}
  alipayPublicKey: ${ALIPAY_PUBLIC_KEY:}
  notifyUrl: ${NOTIFY_URL:}

swagger2:
  #test.frp.dbg-dev.icu:8000
  host: ${SWAGGER2_HOST:127.0.0.1:8910}
