server:
  port: 80
  #servlet:
    #context-path: "/v1"
spring:
  application:
    name: dbg-service-upload
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  #cloud:
  #  nacos:
  #    discovery:
  #      server-addr: ${NACOS_SERVER_ADDR:}
  #      ip: ${NACOS_CLIENT_ADDR:}

#dubbo:
#  registry:
#    address: spring-cloud://localhost
#  cloud:
#    subscribed-services: dbg-service-content

fileUpload:
  rootDir: ${ROOT_DIR:E:\upload}
  imagesDir: ${IMAGES_DIR:\images\}
  tempDir: ${IMAGES_DIR:\temp\}
  gameRomDir: ${GAME_ROM_DIR:\game\rom}

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:club/dbg/cms/login/dao/mapper/*.xml

logging:
  config: classpath:logback-spring.xml
  path: ./logs

stableDiffusion:
  privateKey: ${STABLE_DIFFUSION_PRIVATE_KEY:123456789}
  uploadUrl: ${STABLE_DIFFUSION_UPLOAD_URL:https://api.ddbbgg.com:9800/v1/stable-diffusion/upload-image}
  getTaskUrl: ${STABLE_DIFFUSION_GET_TASK_URL:https://api.ddbbgg.com:9800/v1/stable-diffusion/task}